### ISSUE TITLE
朋友我读了你的dockerfile

### ISSUE THREAD

**Issue by hezhefly** [luckyluckydadada/Lucky-docker#1]
朋友我读了你的dockerfile，不明觉厉，但安装完NVC以后，有哪些启动方式呢，启动后是什么样子的。

**Comment by luckyluckydadada** [comment]
假如你只建立一个容器，ID是0，那么你用vncviewer 链接docker里的vnc界面，访问地址  ip：30004。建立第二个容器，ID是1，那么你用vncviewer 链接docker里的vnc界面，访问地址  ip：30014。一般vnc访问，不用加端口号默认是5901，但是一台机器多个容器，每个容器都是5901端口！怎能区分呢？所以需要端口映射，第一个容器里的5901就是宿主机的30004，第二个容器的5901是30014。所以另一台机器访问这台机器的容器1就是ip：30004，访问容器2就是ip：30014。注意不要省略端口号。

**Comment by luckyluckydadada** [comment]
> 朋友我读了你的dockerfile，不明觉厉，但安装完NVC以后，有哪些启动方式呢，启动后是什么样子的。

假如你只建立一个容器，ID是0，那么你用vncviewer 链接docker里的vnc界面，访问地址 ip：30004。建立第二个容器，ID是1，那么你用vncviewer 链接docker里的vnc界面，访问地址 ip：30014。一般vnc访问，不用加端口号默认是5901，但是一台机器多个容器，每个容器都是5901端口！怎能区分呢？所以需要端口映射，第一个容器里的5901就是宿主机的30004，第二个容器的5901是30014。所以另一台机器访问这台机器的容器1就是ip：30004，访问容器2就是ip：30014。注意不要省略端口号。
